//@version=4
study("Keltner Channel on Timeframe", overlay=true)

var ttf_res = input(title="Timeframe", type=input.resolution, defval="240")

// BEGIN KELTNER CHANNEL
var kc_true_range = input(title="Use True Range", defval=true)
var kc_len = input(title="Length", defval=21)
var kc_mul = input(title="Multiplicator", defval=1.8)
var kc_ema = input(title="Use EMA", defval=true)

kc_center = ema(close, kc_len)
kc_range = kc_true_range ? tr : high - low
kc_range_ema = ema(kc_range, kc_len)
kc_upper = kc_center + kc_range_ema * kc_mul
kc_lower = kc_center - kc_range_ema * kc_mul

kc_upper_htf = security(syminfo.tickerid, ttf_res, kc_upper)
kc_lower_htf = security(syminfo.tickerid, ttf_res, kc_lower)
kc_center_htf = security(syminfo.tickerid, ttf_res, kc_center)

plot(kc_upper_htf, title="Upper")
plot(kc_lower_htf, title="Lower")
plot(kc_center_htf, title="Center")
